### ISSUE TITLE
Can i use TinderView in api lever 14

### ISSUE THREAD

**Issue by yangyu5646** [GadgetCheck/TinderView#1]
I want use this in api level 14.There are some error in studio.
In class CardAnimator 54 line .

baseLayout = new RelativeLayout.LayoutParams(baseLayout);
there is no this method RelativeLayout.LayoutParams(RelativeLayout.LayoutParams source),in api lever 14. Can you give some advise to me ?

**Comment by GadgetCheck** [comment]
Hi, thanks for asking me that.

Your answer is No, it cant be i have only supported API19 and above.
There are a few reasons for the same one of the most important i have used some LayoutParams that are copied with utility functions, which is not available on 19 or below.

But there are some work around to make it work on api 14 as well but as of now i am short of time to work on it (you can send me a pull request if you are able to make it work), since i developed this based on my needs i wanted to keep support for API 19+ devices.

**Comment by yangyu5646** [comment]
ok ,thank you . I will try
